config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'

  resource :admin do
  end

  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :products

  validates :name, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
  belongs_to :country
  before_save {self.name = self.name.titleize}

  validates :name, presence: true

  # this is country_of_origin, not country_of_origins_id because of some rails magic
  # validates :country_id, presence: true

  validates :cost, presence: true

  scope :most_recent, -> {order(:created_at).limit(5)}

  scope :usa_only, -> {where(country_id: Country.find_by_name("USA").id.to_s)}


  # ok so there is not really a great way to do most reviewed, documentation suggests counter_cache: true but that doesn't really work for some reason
  scope :most_reviewed, -> {
    # get ready to count products id
    # add in the reviews
    # group them by product id
    # sort them by the most counted ID
    select("products.id, count(products.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
  }


  # def self.most_reviewed
  #   # get all the products
  #   products = Product.all
  #   most_reviewed_product = nil
  #   most_reviewed_count = 0
  #   products.each do |p|
  #     # establish how many reviews there are for the product
  #     current_review_count = p.reviews.count
  #     # if this product has more reviews than the currently most reviewed product, update that variable
  #     if current_review_count > most_reviewed_count
  #       most_reviewed_product = p
  #       most_reviewed_count = current_review_count
  #     end
  #   end
  #   return most_reviewed_product
  # end

  # finds all ratings, sums them, then divides sum by review count
  def average_rating
    reviews = self.reviews
    rating_sum = 0
    reviews.each do |r|
      rating_sum += r.rating.to_i
    end
    rating = (rating_sum/(self.reviews.count).to_f).round(1)
    return rating
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :user_id, presence: true
  validates :product_id, presence: true
  validates :content_body, presence: true, length: {minimum: 50, maximum: 250}
  validates :rating, presence: true, numericality: { only_integer: true, minimum: 1, maximum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def show
    @countries = Country.all
    @products = Product.all
    render :edit_products
  end

  def create
    # this has to be here for the refresh
    @countries = Country.all
    name = params[:name]
    price = params[:price]
    country_id = params["Country of Origin"].to_i
    product = Product.new(:name => name, :cost => price, :country_id => country_id)
    # used to have a create! here buuuut it would bug out the entire app if it failed validation
    #so now we check if it's valid separately, then save it
    if product.valid?
      product.save
      flash[:notice] = {:message => "#{name} added successfully!", :class => "alert alert-success"}
      redirect_to :controller => 'admins', :action => 'show'
    else
      flash[:bad] = {:message => "Whoops! Try again!", :class => "alert alert-danger"}
      redirect_to :controller => 'admins', :action => 'show'
    end



  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @countries = Country.all
    @products = Product.all
    render :index
  end

  def show
    id = params[:id]
    @product = Product.find(id)
    country_id = @product.country_id
    @country = Country.find(country_id)
    @reviews = Review.where("product_id =#{id}")
    render :product
  end

  def destroy
    id = params[:id]
    @product = Product.find(id)
    @product.destroy
    @reviews = Review.where("product_id = #{id}")
    @reviews.destroy_all
    redirect_to admin_path
  end

  def update
    id = params[:id]
    update_name = params[:name]
    update_cost = params[:cost].delete!("$").to_f
    @product = Product.find(id)
    @product.name = update_name
    @product.cost = update_cost
    @product.save
    redirect_to admin_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :only => [:create]

  def create

    @product = Product.find(params[:product_id])
    content_body = params[:content_body]
    rating = params[:rating]
    review = current_user.reviews.new(:content_body => content_body, :rating => rating, :product_id => @product.id)
    if review.save
      flash[:notice] = {:message=>"Thanks! Your review for #{@product.name} has been added!", :class=>"alert alert-success"}
      redirect_to product_path(@product)
    else
      flash[:notice] = {:message=>review.errors.full_messages, :class=>"alert alert-danger"}
      redirect_to product_path(@product)
    end

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    render :index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/edit_products.html.erb
<% if flash[:notice] %>
<div class="<%= flash[:notice]["class"] %>">
  <%= flash[:notice]["message"] %>
</div>
<% end %>

<% if flash[:bad] %>
<div class="<%= flash[:bad]["class"] %>">
  <%= flash[:bad]["message"] %>
</div>
<% end %>

<h3>Edit Product List</h3>
<hr>
<div class="row">
  <div class="col-md-4"

    <%= form_tag(class:"form-group", method:"post") do %>
      <h4>Add Product</h4>
      <%= label_tag "Product Name:" %>
      <%= text_field_tag :name %>
      <%= label_tag "Price:" %>
      <%= text_field_tag :price %>
      <%= label_tag "Country of Origin:" %>
      <%= select_tag "Country of Origin", options_from_collection_for_select(@countries, "id", "name")%>
      <%= submit_tag "Add Product" %>
    <% end %>
    <fade/>
  </div>
  <hr>
  <div class="col-md-4">
    <% if @products.any? %>
    <div style="overflow: scroll; height:400px;">
      <h4>Delete Products</h4>

        <% @products.each do |p| %>
          <div class="container">
            <%= p.name %>

              <%= link_to "Delete ", product_path(p), :method=>"delete", :class=>"btn btn-danger btn-sm" %>

            <hr>
          </div>
        <% end %>

    </div>
    <% end %>
    <fade/>
  </div>
  <div class="col-md-4">
    <% if @products.any? %>
      <div style="overflow: scroll; height:400px;">
        <h4>Update Product Info</h4>
          <% @products.each do |p| %>
            <%= form_tag product_path(p), method:"patch" do %>
              <div class="container">
                <%= label_tag "Product name" %>
                <%= text_field_tag :name, p.name %>
                <%= label_tag "Country of Origin" %>
                <%= text_field_tag :country, @countries.find_by_id(p.country_id).name %>
                <%= label_tag "Price" %>
                <%= text_field_tag :cost, "$#{p.cost.to_f}" %>
                <%= submit_tag "Update",:class=>"btn btn-danger btn-sm" %>
              </div>
              <hr>
            <% end %>
          <% end %>
      </div>
    <% end %>
    <fade/>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>It's-a Me, Mario's Specialty Food Products</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
  </head>

  <body>
    <div class="navbar">
      <h1 class="navbar-brand">Specialty Food Products</h1>
      <nav class="">

          <%= link_to 'Home', root_path, :class=>"" %>
          |
          <%= link_to 'Products', products_path, :class=>""%>
          |
          <% if !current_user %>
            <%= link_to 'Sign Up', new_user_registration_path, :class=>""  %>
            |
            <%= link_to 'Sign In', new_user_session_path %>
          <% else %>
            <% if current_user.admin == true %>
              <%= link_to 'Admin', admin_path %>
              |
            <% end %>
            <%= current_user.email %>
            |
            <%= link_to 'Sign Out', destroy_user_session_path, :method=>"delete" %>

          <% end %>

        <%= form_tag('/products', method:"post", class:"", style:"float: right;") do%>
          <%= text_field_tag(:search)%>
          <%= submit_tag('Search') %>
        <% end %>
      </nav>
    </div>
    <div class="container">
      <hr>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<div class="container">
  <h2>Products Available:</h2>
  <% if @products.any? %>
    <div class="card-columns">

      <% @products.each do |p| %>
        <div class="card">
          <div class="card-body">
            <h3 class="card-title"><%=link_to p.name, product_path(p) %></h3>
            <p>From <%= @countries.find_by_id(p.country_id).name  %></p>
            <p>Rating: <%= p.average_rating %> </p>
            <p>Description: <%= Faker::Coffee.notes %></p>
          </div>
        </div>
      <% end %>

    </div>
  <% end %>
</div>

app/views/products/product.html.erb
<div class="container">
  <div class="card product-display">
    <div class="card-body">
      <h2 class="card-title"><%= @product.name %></h2>
      <p>From: <%= @country.name %></p>
      <p>Price: $<%= @product.cost %> <%= link_to 'Buy Now', "#", :class=>"btn btn-success btn-sm" %></p>

      <%= image_tag 'https://picsum.photos/300/300' %>

      <div class="form-holder">
        <%= form_tag product_reviews_path(@product) do %>
          <h4>Review Product</h4>

          <% if flash[:notice] %>


            <% if flash[:notice]["message"].size ==  2 %>
              <%   flash[:notice]["message"].each do |m| %>
              <div class="<%= flash[:notice]["class"] %>">
                <%= m %>
              </div>
              <% end %>

            <% else %>

              <div class="<%= flash[:notice]["class"] %>">

                <%= flash[:notice]["message"] %>
              </div>
            <% end %>


          <% end %>

          <%= label_tag 'Rating' %>
          <%= select_tag :rating, options_for_select([ "1", "2", "3", "4", "5" ], "5") %>
          <%= label_tag 'Review:' %>
          <%= text_area_tag :content_body%>
          <%= submit_tag "Add Review", :class=>"btn btn-primary" %>
        <% end %>

      </div>
    </div>
  </div>

  <% if @reviews.any? %>
    <div class="card-columns">

      <% @reviews.each do |r| %>
      <div class="card">
        <div class="card-body">
          <h3><%=User.find(r.user_id).username%></h3>
          <h4>Rating: <%= r.rating %></h4>
          <p> <%= r.content_body %></p>
        </div>
      </div>
      <% end %>

    </div>
  <% end %>

</div>

app/views/welcome/index.html.erb
<div class="container">
  <h3>Welcome to Specialty Food Products!</h3>
  <h4>Most Reviewed Product: <%= link_to Product.most_reviewed.name, product_path(Product.most_reviewed) %></h2>
  <h4>Most Recent Products Added:</h2>

  <% if Product.most_recent.any? %>
  <% @most_recent = Product.most_recent %>
  <div class="card-columns">
    <% @most_recent.each do |p| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= link_to p.name, product_path(p) %></h3>
        <p>Rating: <%= p.average_rating %></p>
        <p class="card-text"><%= Faker::Coffee.notes %></p>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
</div>